/**
 * Servicio de Datos Simulados
 * Proporciona datos ficticios para pruebas
 */

export const mockStores = [
  {
    id: 1,
    name: 'Súper Mercado Central',
    latitude: 40.7128,
    longitude: -74.006,
    address: '123 Main St',
    type: 'supermarket',
    rating: 4.5,
    reviews: 245,
  },
  {
    id: 2,
    name: 'Tienda Local Express',
    latitude: 40.7258,
    longitude: -74.0076,
    address: '456 Park Ave',
    type: 'local',
    rating: 4.3,
    reviews: 189,
  },
  {
    id: 3,
    name: 'Mercado Mayorista',
    latitude: 40.7480,
    longitude: -73.9862,
    address: '789 5th Ave',
    type: 'wholesale',
    rating: 4.7,
    reviews: 312,
  },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Leche Fresca 1L',
    price: 2.99,
    bulkPrice: 2.49,
    storeId: 1,
    storeName: 'Súper Mercado Central',
    category: 'dairy',
    rating: 4.6,
    ratingCount: 128,
    description: 'Leche fresca de calidad premium',
    image: '🥛',
    isFeatured: true,
  },
  {
    id: 2,
    name: 'Pan Integral',
    price: 3.49,
    bulkPrice: 2.99,
    storeId: 1,
    storeName: 'Súper Mercado Central',
    category: 'bakery',
    rating: 4.4,
    ratingCount: 95,
    description: 'Pan integral recién horneado',
    image: '🍞',
    isFeatured: true,
  },
  {
    id: 3,
    name: 'Huevos Docena',
    price: 4.99,
    bulkPrice: 3.99,
    storeId: 2,
    storeName: 'Tienda Local Express',
    category: 'dairy',
    rating: 4.8,
    ratingCount: 156,
    description: 'Huevos frescos de granja',
    image: '🥚',
    isFeatured: true,
  },
  {
    id: 4,
    name: 'Tomates Frescos (kg)',
    price: 1.99,
    bulkPrice: 1.49,
    storeId: 3,
    storeName: 'Mercado Mayorista',
    category: 'produce',
    rating: 4.5,
    ratingCount: 203,
    description: 'Tomates frescos y jugosos',
    image: '🍅',
    isFeatured: false,
  },
  {
    id: 5,
    name: 'Manzanas (kg)',
    price: 2.49,
    bulkPrice: 1.99,
    storeId: 3,
    storeName: 'Mercado Mayorista',
    category: 'produce',
    rating: 4.7,
    ratingCount: 189,
    description: 'Manzanas frescas y crujientes',
    image: '🍎',
    isFeatured: true,
  },
];

export const mockPromotions = [
  {
    id: 1,
    storeId: 1,
    title: '20% de descuento en lácteos',
    description: 'Todos los productos lácteos con 20% de descuento',
    discount: 0.2,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    category: 'dairy',
  },
  {
    id: 2,
    storeId: 2,
    title: 'Envío gratis en pedidos mayores a $30',
    description: 'Envío gratis para compras mayores a $30',
    discount: 0,
    freeShipping: true,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    storeId: 3,
    title: '2x1 en frutas seleccionadas',
    description: 'Compra una fruta y lleva dos',
    discount: 0.5,
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    category: 'produce',
  },
];

export const mockSavingsData = [
  { month: 'Enero', withApp: 45.5, withoutApp: 120.0 },
  { month: 'Febrero', withApp: 62.3, withoutApp: 150.5 },
  { month: 'Marzo', withApp: 38.75, withoutApp: 130.2 },
  { month: 'Abril', withApp: 71.2, withoutApp: 165.8 },
  { month: 'Mayo', withApp: 55.9, withoutApp: 145.3 },
  { month: 'Junio', withApp: 48.6, withoutApp: 155.0 },
];
